//! tokenscale — command-line entrypoint.
//!
//! `tokenscale` is a self-hostable local dashboard that reconciles Anthropic
//! usage across two ingest paths: local Claude Code JSONL logs and the
//! Anthropic Admin API. It computes real cost, counterfactual API cost, and
//! environmental impact (energy, water, CO2e) per query and over time.
//!
//! Phase 1 surface:
//!
//! - `tokenscale init`            — create the config file and the database.
//! - `tokenscale scan`            — ingest Claude Code JSONL session logs.
//! - `tokenscale serve`           — start the local HTTP server (Phase 1 next step).
//! - `tokenscale factors update`  — Phase 3 — reserved no-op.
//! - `tokenscale factors publish` — Phase 3 — reserved no-op.

mod config;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use std::net::SocketAddr;
use std::path::PathBuf;
use tokenscale_ingest_cc::run_scan;
use tokenscale_server::{serve, AppState};
use tokenscale_store::Database;
use tracing::info;

use crate::config::{resolve_config_path, Config};

/// Self-hostable Anthropic usage and impact dashboard.
#[derive(Parser, Debug)]
#[command(name = "tokenscale", version, about, long_about = None)]
struct CommandLineArguments {
    /// Path to the configuration TOML. Overrides $TOKENSCALE_CONFIG and the
    /// default at ~/.config/tokenscale/config.toml.
    #[arg(long, env = "TOKENSCALE_CONFIG", global = true)]
    config: Option<PathBuf>,

    #[command(subcommand)]
    command: TopLevelCommand,
}

#[derive(Subcommand, Debug)]
#[command(rename_all = "kebab-case")]
enum TopLevelCommand {
    /// Initialize the local data directory, configuration file, and SQLite schema.
    Init,

    /// Incrementally ingest Claude Code JSONL session logs from ~/.claude/projects/.
    /// Idempotent: re-runs against unchanged files cost only a stat() per file.
    Scan,

    /// Start the local HTTP server and dashboard.
    Serve {
        /// Address to bind. Defaults to localhost-only.
        #[arg(long)]
        bind: Option<String>,
    },

    /// Manage the environmental-factor model. Reserved — Phase 3 surface.
    Factors {
        #[command(subcommand)]
        action: FactorsAction,
    },
}

#[derive(Subcommand, Debug)]
#[command(rename_all = "kebab-case")]
enum FactorsAction {
    /// Pull the upstream factor model from the public Git repo.
    /// Phase 3 — not yet implemented.
    Update,

    /// Publish a locally-edited factor model upstream (maintainer-only).
    /// Phase 3 — not yet implemented.
    Publish,
}

#[tokio::main]
async fn main() -> Result<()> {
    initialize_tracing();
    let arguments = CommandLineArguments::parse();
    let config_path = resolve_config_path(arguments.config.as_deref())?;

    match arguments.command {
        TopLevelCommand::Init => command_init(&config_path).await,
        TopLevelCommand::Scan => command_scan(&config_path).await,
        TopLevelCommand::Serve { bind } => command_serve(&config_path, bind).await,
        TopLevelCommand::Factors { action } => match action {
            FactorsAction::Update | FactorsAction::Publish => {
                println!("Phase 3 — not yet implemented");
                Ok(())
            }
        },
    }
}

/// Configure the tracing subscriber. Honors `RUST_LOG`; defaults to `info`.
fn initialize_tracing() {
    use tracing_subscriber::EnvFilter;
    tracing_subscriber::fmt()
        .with_env_filter(EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()))
        .with_target(false)
        .init();
}

/// Implementation of `tokenscale init`.
///
/// Idempotent: re-running on a configured machine will (a) write a default
/// config only if no file exists, and (b) open the database, which applies
/// any new migrations and is a no-op when the schema is already current.
async fn command_init(config_path: &std::path::Path) -> Result<()> {
    if config_path.exists() {
        info!(path = %config_path.display(), "configuration already present, leaving as-is");
        println!("Config already exists at {}", config_path.display());
    } else {
        if let Some(parent_directory) = config_path.parent() {
            tokio::fs::create_dir_all(parent_directory)
                .await
                .with_context(|| format!("creating {}", parent_directory.display()))?;
        }
        let default_config = Config::default();
        let serialized = default_config.to_toml()?;
        let preamble = "# tokenscale configuration file.\n\
                        # Generated by `tokenscale init`. See README and docs/ for the field reference.\n\n";
        tokio::fs::write(config_path, format!("{preamble}{serialized}"))
            .await
            .with_context(|| format!("writing {}", config_path.display()))?;
        info!(path = %config_path.display(), "wrote default configuration");
        println!("Wrote default config to {}", config_path.display());
    }

    let config = Config::load_or_default(config_path)?;
    let database_path = config.effective_database_path()?;
    let database = Database::open(&database_path)
        .await
        .with_context(|| format!("opening database at {}", database_path.display()))?;
    drop(database);
    info!(path = %database_path.display(), "database initialized");
    println!("Database initialized at {}", database_path.display());
    Ok(())
}

/// Implementation of `tokenscale serve`.
///
/// Bind precedence: `--bind` flag > config `[server].bind` > built-in default
/// `127.0.0.1:8787`. The default is loopback-only because the Phase 1 build
/// has no auth.
async fn command_serve(config_path: &std::path::Path, bind_override: Option<String>) -> Result<()> {
    let config = Config::load_or_default(config_path)?;
    let database_path = config.effective_database_path()?;
    let database = Database::open(&database_path)
        .await
        .with_context(|| format!("opening database at {}", database_path.display()))?;

    let bind_string = bind_override.unwrap_or_else(|| config.server.bind.clone());
    let bind_address: SocketAddr = bind_string
        .parse()
        .with_context(|| format!("parsing bind address {bind_string:?}"))?;

    info!(address = %bind_address, "starting tokenscale server");
    serve(AppState::new(database), bind_address).await
}

/// Implementation of `tokenscale scan`.
async fn command_scan(config_path: &std::path::Path) -> Result<()> {
    let config = Config::load_or_default(config_path)?;
    let database_path = config.effective_database_path()?;
    let database = Database::open(&database_path)
        .await
        .with_context(|| format!("opening database at {}", database_path.display()))?;

    let claude_code_root = config.effective_claude_code_root()?;
    let summary = run_scan(&database, &claude_code_root, config.ingest.store_raw)
        .await
        .context("running Claude Code scan")?;

    println!(
        "Scan complete: {} files seen, {} parsed, {} unchanged. {} new events, {} duplicates skipped. {} non-assistant lines, {} malformed.",
        summary.files_seen,
        summary.files_parsed,
        summary.files_unchanged,
        summary.events_inserted,
        summary.events_duplicates,
        summary.lines_skipped,
        summary.lines_malformed
    );
    Ok(())
}
